name: Warpstones
version: 1.4
description: A uniquely immersive warping system, based around floating structures known as Warpstones.
author: Kyle Nanakdewa
website: https://plugins.akenland.com

api-version: 1.14
main: com.kylenanakdewa.warpstones.WarpstonesPlugin
depend: [CoRE]
softdepend: [WorldEdit]

commands:
  warpstones:
    description: Manage Warpstones
    aliases: [ws]
  warp:
    description: Warp to a Warpstone
    usage: "Usage: /warp <Warpstone ID>"
  home:
    description: Warp to your home bed
  spawn:
    description: Warp to the server spawn
  tp:
    description: Teleport to another player
    usage: "Usage: /tp <player>"
  tphere:
    description: Teleport another player to you
    usage: "Usage: /tphere <players...>"