name: Warpstones
version: 1.3
description: A uniquely immersive warping system, based around floating structures known as Warpstones.
author: Kyle Nanakdewa
website: https://plugins.akenland.com

api-version: 1.14
main: com.kylenanakdewa.warpstones.WarpstonesPlugin
depend: [CoRE]
softdepend: [WorldEdit]

commands:
  warpstones:
    description: Warp to a warpstone
    aliases: [ws, warp, home, last, spawn]
  tp:
    description: Teleport to another player
    aliases: [tpa]
    usage: "Usage: /tp <player>"
  tphere:
    description: Teleport another player to you
    aliases: [tpahere]
    usage: "Usage: /tphere <players...>"
