name: Warpstones
version: 1.2pre
description: A uniquely immersive warping system, based around floating structures known as Warpstones.
author: Kyle Nanakdewa
website: http://plugins.akenland.com

main: com.kylenanakdewa.warpstones.WarpstonesPlugin
depend: [CoRE]
softdepend: [WorldEdit]

commands:
  warpstones:
    description: Warp to a warpstone
    aliases: [warpstone, ws, warp, home, last, spawn, sethome]
  tp:
    description: Teleport to another player
    aliases: [tpa]
    usage: "Usage: /tp <player>"
  tphere:
    description: Teleport another player to you
    aliases: [tpahere]
    usage: "Usage: /tphere <players...>"
